{
 "title": "FastAPI Observability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"task-manager-backend\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count by Endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"task-manager-backend\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"task-manager-backend\"} / http_request_duration_seconds_count{job=\"task-manager-backend\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total 5xx Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"task-manager-backend\", status=~\"5..\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"task-manager-backend\", status=\"2xx\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"task-manager-backend\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"task-manager-backend\", status=\"5xx\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"task-manager-backend\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "P99 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"task-manager-backend\", handler!=\"/metrics\"}[1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Per Second (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"task-manager-backend\", handler!=\"/metrics\"}[1m])",
     "legendFormat": "{{pod}} {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Backend Replicas (HPA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"task-manager\", deployment=\"backend\"}",
     "legendFormat": "replicas"
    }
   ]
  }
 ]
}