sonar.projectKey=task-manager-frontend
sonar.projectName=Task Manager Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/test/**,src/**/*.d.ts,src/main.tsx,src/vite-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
