services:
  db:
    image: postgres:16-alpine
    container_name: task-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: cr.yandex/crp10m317mg7ppiikck3/task-manager-backend:latest
    container_name: task-manager-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    image: cr.yandex/crp10m317mg7ppiikck3/task-manager-frontend:latest
    container_name: task-manager-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db-data:
